/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsTictactoeRouteImport } from './routes/projects/tictactoe'
import { Route as ProjectsHtmlRouteImport } from './routes/projects/html'
import { Route as ProjectsHangmanRouteImport } from './routes/projects/hangman'
import { Route as ProjectsCssRouteImport } from './routes/projects/css'
import { Route as ProjectsCalculatorRouteImport } from './routes/projects/calculator'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsTictactoeRoute = ProjectsTictactoeRouteImport.update({
  id: '/tictactoe',
  path: '/tictactoe',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsHtmlRoute = ProjectsHtmlRouteImport.update({
  id: '/html',
  path: '/html',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsHangmanRoute = ProjectsHangmanRouteImport.update({
  id: '/hangman',
  path: '/hangman',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsCssRoute = ProjectsCssRouteImport.update({
  id: '/css',
  path: '/css',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsCalculatorRoute = ProjectsCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => ProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/test': typeof TestRoute
  '/projects/calculator': typeof ProjectsCalculatorRoute
  '/projects/css': typeof ProjectsCssRoute
  '/projects/hangman': typeof ProjectsHangmanRoute
  '/projects/html': typeof ProjectsHtmlRoute
  '/projects/tictactoe': typeof ProjectsTictactoeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/test': typeof TestRoute
  '/projects/calculator': typeof ProjectsCalculatorRoute
  '/projects/css': typeof ProjectsCssRoute
  '/projects/hangman': typeof ProjectsHangmanRoute
  '/projects/html': typeof ProjectsHtmlRoute
  '/projects/tictactoe': typeof ProjectsTictactoeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/test': typeof TestRoute
  '/projects/calculator': typeof ProjectsCalculatorRoute
  '/projects/css': typeof ProjectsCssRoute
  '/projects/hangman': typeof ProjectsHangmanRoute
  '/projects/html': typeof ProjectsHtmlRoute
  '/projects/tictactoe': typeof ProjectsTictactoeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/test'
    | '/projects/calculator'
    | '/projects/css'
    | '/projects/hangman'
    | '/projects/html'
    | '/projects/tictactoe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/test'
    | '/projects/calculator'
    | '/projects/css'
    | '/projects/hangman'
    | '/projects/html'
    | '/projects/tictactoe'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/test'
    | '/projects/calculator'
    | '/projects/css'
    | '/projects/hangman'
    | '/projects/html'
    | '/projects/tictactoe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  TestRoute: typeof TestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/tictactoe': {
      id: '/projects/tictactoe'
      path: '/tictactoe'
      fullPath: '/projects/tictactoe'
      preLoaderRoute: typeof ProjectsTictactoeRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/html': {
      id: '/projects/html'
      path: '/html'
      fullPath: '/projects/html'
      preLoaderRoute: typeof ProjectsHtmlRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/hangman': {
      id: '/projects/hangman'
      path: '/hangman'
      fullPath: '/projects/hangman'
      preLoaderRoute: typeof ProjectsHangmanRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/css': {
      id: '/projects/css'
      path: '/css'
      fullPath: '/projects/css'
      preLoaderRoute: typeof ProjectsCssRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/calculator': {
      id: '/projects/calculator'
      path: '/calculator'
      fullPath: '/projects/calculator'
      preLoaderRoute: typeof ProjectsCalculatorRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsCalculatorRoute: typeof ProjectsCalculatorRoute
  ProjectsCssRoute: typeof ProjectsCssRoute
  ProjectsHangmanRoute: typeof ProjectsHangmanRoute
  ProjectsHtmlRoute: typeof ProjectsHtmlRoute
  ProjectsTictactoeRoute: typeof ProjectsTictactoeRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsCalculatorRoute: ProjectsCalculatorRoute,
  ProjectsCssRoute: ProjectsCssRoute,
  ProjectsHangmanRoute: ProjectsHangmanRoute,
  ProjectsHtmlRoute: ProjectsHtmlRoute,
  ProjectsTictactoeRoute: ProjectsTictactoeRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  TestRoute: TestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
